---
slug: :list_for_profile
depends:
  mikutter: '5.0'
  plugin:
  - list
  - gtk3
  - gui
  - uitranslator
  - skin
version: '2.0'
author: toshi_a
name: プロフィール用リストタブ
description: ユーザのプロフィール画面に、リスト管理用のタブを表示します
