---
slug: :list_for_profile
depends:
  mikutter: '3.1'
  plugin:
  - list
  - gtk
  - gui
  - uitranslator
  - skin
version: '1.0'
author: toshi_a
name: プロフィール用リストタブ
description: ユーザのプロフィール画面に、リスト管理用のタブを表示します
